language: python

python:
  - "3.4"

sudo: required

before_install:
- "sudo apt-get install graphviz"
- mkdir _website
- cd _website
- "git clone -b gh-pages http://github.com/useblocks/presentations ."
- cd ..

install:
  - "pip install sphinx"
  - "pip install sphinxcontrib-plantuml"
  - "pip install sphinxjp.themes.revealjs"
  - "pip install sphinxcontrib-googlechart"


script:
  - cd presentations
  - make html

after_success:
  - git config --global user.name "Daniel Woste"
  - git config --global user.email "daniel.woste@useblocks.com"
  - git config --global push.default simple
  - cp build/* ../_website
  - cd ../_website
  - touch .nojekyll
  - git add -A
  - git commit -m "Updated useblocks presentations website via travisci"
  - git push origin gh-pages
