language: python

python:
  - "2.7"

sudo: required

before_install:
- eval `ssh-agent -s`
- "sudo apt-get install graphviz"
- mkdir _website
- cd _website
- "git clone -b gh-pages http://github.com/useblocks/presentations ."
- cd ..

install:
  - "pip install sphinx"
  - "pip install sphinxcontrib-plantuml"
  - "pip install sphinxjp.themes.revealjs"
  - "pip install sphinxcontrib-googlechart"


script:
  - cd presentations
  - make html

after_success:
  - git config --global user.name "Daniel Woste"
  - git config --global user.email "daniel.woste@useblocks.com"
  - git config --global push.default simple
  - cp -r build/html/* ../_website
  - cd ../_website
  - touch .nojekyll
  - git add -A
  - git commit -m "Updated useblocks presentations website via travisci"
  - echo $DEPLOY_KEY > .travis/deploy_key.pem
  - chmod 600 .travis/deploy_key.pem # this key should have push access
  - ssh-add .travis/deploy_key.pem
  - git remote add deploy https://danwos@github.com/useblocks/presentations
  - git push deploy gh-pages
