language: python

python:
  - "2.7"

sudo: required

before_install:
- git config --global user.name "Daniel Woste"
- git config --global user.email "daniel.woste@useblocks.com"
- git config --global push.default simple
- "sudo apt-get install graphviz"
- mkdir _website
- cd _website
- "git clone -b gh-pages http://github.com/useblocks/presentations ."
- cd ..

install:
  - "pip install sphinx"
  - "pip install sphinxcontrib-plantuml"
  - "pip install sphinxjp.themes.revealjs"
  - "pip install sphinxcontrib-googlechart"


script:
  - cd presentations
  - make html
  - cd ..
  - cp -r presentations/build/html/* _website/
  - cd _website
  - touch .nojekyll
  - git add -A
  - git commit -m "Updated useblocks presentations website via travisci"
  - git push --force --quiet "https://$DEPLOY_KEY@github.com/useblocks/presentations gh-pages" > /dev/null 2>&1

after_success:

