@startuml

' general
skinparam backgroundColor white

' component
skinparam componentFontSize 30
skinparam interfaceFontSize 20
skinparam interfaceFontStyle bold
skinparam nodeFontSize 25

' object
skinparam objectFontSize 17
skinparam objectAttributeFontSize 14



' useblocks yellow
!define COLOR1 #FFCC00

' red
!define COLOR2 #E44424

' blue
!define COLOR3 #67BCDB

' green
!define COLOR4 #A2AB58


@enduml