@startuml
!include config.puml

object Metrics {
As many as you can get
}

object Report {
Huge Excel-Report
}

object eMail {
One eMail to rule them all
}

object Users {
Developers, Teamleaders, Managers, ...
}
Metrics -> Report
Report -> eMail
eMail -> Users
@enduml