@startuml
!include config.puml

object Metriken {
Zuviel mitnehmen \lwie möglich
}

object Report {
Alles in einen großen \lExcel-Report packen
}

object eMail {
Eine einzelne E-Mail an \lwirklich Alle verschicken
}

object Mitarbeiter {
Developers, Teamleaders,\lManagers, ...
}
Metriken -> Report
Report -> eMail
eMail -> Mitarbeiter

@enduml