@startuml
!include config.puml

object Metrics {
Take only what your customers need
}

object DeveloperReport COLOR2 {
automatically update weekly
}

object ManagementReport COLOR2 {
automatically update monthly
}

object eMail COLOR1 {
Send as Excel-Export
}

object Wiki COLOR1 {
Create a new report page
}

object Dashboard COLOR1 {
Integrate in the Ticket-System Dashboard
}

object Chat COLOR1 {
Send link to Team-Channel
           }

object Webhook COLOR1 {
Inform external Service
}

object Developer COLOR3
object Teamleader COLOR3
object Manager COLOR3
object Service COLOR3

Metrics --> DeveloperReport
Metrics --> ManagementReport
DeveloperReport --> Wiki
DeveloperReport --> Chat
DeveloperReport --> Dashboard

ManagementReport --> eMail
ManagementReport --> Webhook

Wiki --> Developer
Wiki --> Teamleader
Wiki --> Manager
Chat --> Developer
Chat --> Teamleader
Dashboard --> Teamleader
eMail --> Manager
Webhook --> Service

@enduml