@startuml
!include config.puml

object Metriken {
Nur das nehmen, was die Kunden brauchen
}

object EntwicklerReport COLOR2 {
Mit jedeM CodePUSH ein Update
}

object ManagementReport COLOR2 {
Wöchentliche, automatische Updates
}

object eMail COLOR1 {
Angehängter Excel-Report
}

object Wiki COLOR1 {
Anlage einer neuen Report-Seite
}

object Dashboard COLOR1 {
Integrieren ins Dashboard \ldes Ticket-Systems
}

object Chat COLOR1 {
Poste Probleme und Report-Link \lins Team-Chat
}

object Webhook COLOR1 {
Externen Service informieren
}

object Entwickler COLOR3
object Teamleiter COLOR3
object Manager COLOR3
object Service COLOR3

Metriken --> EntwicklerReport
Metriken --> ManagementReport
EntwicklerReport --> Wiki
EntwicklerReport --> Chat
EntwicklerReport --> Dashboard

ManagementReport --> eMail
ManagementReport --> Webhook

Dashboard --> Entwickler
Wiki --> Teamleiter
Wiki --> Manager
Chat --> Entwickler
Dashboard --> Teamleiter
eMail --> Manager
Webhook --> Service

@enduml