@startuml
!include config.puml
object collection COLOR3
object storage COLOR4
object dashboard COLOR2

object datablocks COLOR1
object distribution
object alarms
object knowledge

collection -> storage
storage -> dashboard
storage --> datablocks
datablocks ..> dashboard
datablocks ..> collection
datablocks -> distribution
datablocks -left> alarms
datablocks -up-> knowledge
@enduml